from __future__ import annotations

import chromadb  # Used to create and manage the ChromaDB vector database.

from src.embeddings import EmbeddedChunk


class VectorDB:
    """Stores and retrieves document embeddings using ChromaDB."""

    def __init__(
        self,
        persist_path: str = "./chroma_db",
        collection_name: str = "knowledge_base",
    ) -> None:
        """
        Initialize the persistent ChromaDB collection.

        Args:
            persist_path:
                Folder where the vector database will be stored.

            collection_name:
                Name of the collection used to store document chunks.
        """

        self.client = chromadb.PersistentClient(
            path=persist_path
        )
        # Creates a persistent ChromaDB client that saves data to disk.

        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"},
        )
        # Creates the collection if it does not already exist.
        # Cosine distance is used to compare embedding similarity.

    def add_documents(
        self,
        ids: list[str],
        embeddings: list[list[float]],
        documents: list[str],
        metadatas: list[dict],
    ) -> None:
        """
        Add document texts, embeddings, and metadata to ChromaDB.
        """

        if not (
            len(ids)
            == len(embeddings)
            == len(documents)
            == len(metadatas)
        ):
            raise ValueError(
                "ids, embeddings, documents, and metadatas "
                "must have the same length."
            )

        if not ids:
            return

        self.collection.add(
            ids=ids,
            embeddings=embeddings,
            documents=documents,
            metadatas=metadatas,
        )
        # Stores all document data inside the vector database.

    def add_embedded_chunks(
        self,
        embedded_chunks: list[EmbeddedChunk],
    ) -> None:
        """
        Store EmbeddedChunk objects directly in ChromaDB.

        Args:
            embedded_chunks:
                Chunks generated by embeddings.py.
        """

        if not embedded_chunks:
            return

        ids: list[str] = []
        embeddings: list[list[float]] = []
        documents: list[str] = []
        metadatas: list[dict] = []

        for index, chunk in enumerate(
            embedded_chunks,
            start=1,
        ):
            document_name = chunk.metadata.get(
                "document_name",
                "document",
            )

            page_number = chunk.metadata.get(
                "page_number",
                "none",
            )

            chunk_number = chunk.metadata.get(
                "chunk_number",
                index,
            )

            chunk_id = (
                f"{document_name}-"
                f"page-{page_number}-"
                f"chunk-{chunk_number}"
            )
            # Creates a unique ID using document, page, and chunk data.

            ids.append(chunk_id)
            embeddings.append(chunk.embedding)
            documents.append(chunk.text)
            metadatas.append(chunk.metadata.copy())

        self.add_documents(
            ids=ids,
            embeddings=embeddings,
            documents=documents,
            metadatas=metadatas,
        )
        # Sends the prepared data to the main add method.

    def query(
        self,
        query_embedding: list[float],
        n_results: int = 5,
        where: dict | None = None,
    ) -> dict:
        """
        Search for the most similar stored chunks.

        Args:
            query_embedding:
                Embedding vector generated from the user question.

            n_results:
                Maximum number of results to return.

            where:
                Optional metadata filter.

        Returns:
            ChromaDB query response containing documents,
            metadata, and distances.
        """

        if not query_embedding:
            raise ValueError(
                "query_embedding cannot be empty."
            )

        if n_results < 1:
            raise ValueError(
                "n_results must be greater than 0."
            )

        return self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            where=where,
        )
        # Searches the collection using the question embedding.

    def count(self) -> int:
        """Return the number of stored chunks."""

        return self.collection.count()